name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd electron-app
          npm install

      - name: Build Electron app
        run: |
          cd electron-app
          npm run build

      - name: Package Electron app
        run: |
          cd electron-app
          npm run package

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: electron-app
          path: electron-app/dist/**/*